Completed prep-css-flexbox
ayshahussain141/prep-0922-code-solutions pull request #8
Opened 2022-09-24 02:50 UTC by ayshahussain141

<img width="960" alt="Screenshot 2022-09-23 222958" src="https://user-images.githubusercontent.com/46547520/192076981-04cdc331-d19b-4c8f-b151-31ebde393c88.png">
<img width="651" alt="Screenshot 2022-09-23 223648" src="https://user-images.githubusercontent.com/46547520/192076982-f73a0cf4-bcbf-4321-8c69-5a67bc4ae343.png">
<img width="907" alt="Screenshot 2022-09-23 222514" src="https://user-images.githubusercontent.com/46547520/192076983-4be393f9-34c5-4ce5-a7ec-0f116faf77cb.png">
<img width="641" alt="Screenshot 2022-09-23 224438" src="https://user-images.githubusercontent.com/46547520/192076984-18193898-4bec-4e67-9641-a6a192e333cc.png">

2022-09-24 15:00 UTC, thebearingedge requested changes
Hi Aysha, please see my notes. For this assignment we want to use flex-basis only on "flex items", so that property will need to be moved to a rule set for `.card-wrapper`

2022-09-24 15:00 UTC, thebearingedge commented on prep-css-flexbox/align-items.html
> +    }
For this assignment we don't want to make all divs display-flex, just the #card-deck

2022-09-24 15:00 UTC, thebearingedge commented on prep-css-flexbox/align-items.html
> +      flex-basis: calc(100%/3);
flex-basis is only meant for "flex items" so you'll want to use it in a rule set for `.card-wrapper`.

2022-09-24 23:10 UTC, ayshahussain141 commented
<img width="943" alt="Screenshot 2022-09-24 190208" src="https://user-images.githubusercontent.com/46547520/192121722-94b38d74-3bae-4b0f-8735-d50fb8488fce.png">
<img width="623" alt="Screenshot 2022-09-24 190020" src="https://user-images.githubusercontent.com/46547520/192121723-81eb9859-3b98-49d1-a18e-0cff97944b58.png">
<img width="943" alt="Screenshot 2022-09-24 190146" src="https://user-images.githubusercontent.com/46547520/192121724-21a43339-0115-4f46-af4a-620111bb1c14.png">
<img width="775" alt="Screenshot 2022-09-24 185800" src="https://user-images.githubusercontent.com/46547520/192121726-65b8bb9a-1d9e-435b-9bf0-5a012639d184.png">

2022-09-25 02:43 UTC, thebearingedge approved these changes

2022-09-26 03:08 UTC, merged