Completed prep-css-layout-classes
ayshahussain141/prep-0922-code-solutions pull request #9
Opened 2022-09-24 05:49 UTC by ayshahussain141

<img width="935" alt="Screenshot 2022-09-24 014356" src="https://user-images.githubusercontent.com/46547520/192082197-7a37a169-bd09-48a5-a154-e68137b6b480.png">

2022-09-24 15:07 UTC, thebearingedge requested changes

2022-09-24 15:07 UTC, thebearingedge commented on prep-css-layout-classes/index.html
> +    </div>
Hi Aysha, for this assignment we want to only have one container and one row. The row can have 3 columns and each column will have an image, a heading, and a paragraph.

```html
<div class="container">
  <div class="row">
    <div class="column">
    </div>
    <div class="column">
    </div>
    <div class="column">
    </div>
  </div>
</div>
```

2022-09-24 23:55 UTC, ayshahussain141 commented
<img width="629" alt="Screenshot 2022-09-24 194924" src="https://user-images.githubusercontent.com/46547520/192122724-257eebac-6f73-480c-9be2-4fd602decc23.png">

2022-09-25 02:45 UTC, thebearingedge approved these changes

2022-09-26 03:08 UTC, merged